# Working with QGates

_by Austin Poor_

`qgates` has three submodules: 
* `qgates.states` with some pre-defined common state vectors,
* `qgates.gates` with some pre-defined common gates (logical and quantum), and 
* `qgates.qfn` with helper functions for creating and combining states and gates.

In [1]:
import qgates

## States

`qgates.states` has 10 premade state vectors.

Two single-bit qubits:
* `QB0`: $|0\rangle$
* `QB1`: $|1\rangle$

Four two-bit qubits (which are combinations of the above two):
* `QB00`: $|00\rangle$
* `QB01`: $|01\rangle$
* `QB10`: $|10\rangle$
* `QB11`: $|11\rangle$

The four [Bell states](https://en.wikipedia.org/wiki/Bell_state):
* `BELL00`: $|\Phi^+\rangle$
* `BELL01`: $|\Phi^-\rangle$
* `BELL10`: $|\Psi^+\rangle$
* `BELL11`: $|\Psi^-\rangle$

For example, here are the single qubits...

In [2]:
print("|0> ", qgates.states.QB0)
print("|1> ", qgates.states.QB1)

|0>  [1 0]
|1>  [0 1]


And two of the the 2-qubit pairs...

In [3]:
print("|00> ", qgates.states.QB00)
print("|10> ", qgates.states.QB10)

|00>  [1 0 0 0]
|10>  [0 0 1 0]


## Gates

There are 8 logical/normal-bit gates:
* `IDEN`
* `NOT`
* `AND`
* `OR`
* `XOR`
* `NAND`
* `NOR`
* `COPY`

...and 4 quantum gates:
* `HAD`, the [Hadamard gate](https://en.wikipedia.org/wiki/Quantum_logic_gate#Hadamard_(H)_gate)
* `CNOT`, the [controlled not gate](https://en.wikipedia.org/wiki/Controlled_NOT_gate)
* `TOFFOLI`, the [toffoli gate](https://en.wikipedia.org/wiki/Toffoli_gate) (_aka_ the CCNOT gate)
* `SWAP`, the [swap gate](https://en.wikipedia.org/wiki/Quantum_logic_gate#Swap_(SWAP)_gate)

For example, here are the _identity_ gate and the _not_ gate matrices...

In [4]:
print(qgates.gates.IDEN)

[[1 0]
 [0 1]]


In [5]:
print(qgates.gates.NOT)

[[0 1]
 [1 0]]


And here are the _or_ and _copy_ gates...

In [6]:
print(qgates.gates.OR)

[[1 0 0 0]
 [0 1 1 1]]


In [7]:
print(qgates.gates.COPY)

[[1 0]
 [0 0]
 [0 0]
 [0 1]]


And here are some of the quantum gates...

In [8]:
print(qgates.gates.HAD)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [9]:
print(qgates.gates.CNOT)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [10]:
print(qgates.gates.TOFFOLI)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]


## Helper Functions

There are four functions in the `qgates.qfn` submodule:
* `state` to create state vectors
* `tens` to calculate the [tensor product](https://en.wikipedia.org/wiki/Tensor_product) of two or more states or gates
* `matmul` to perform [matrix multiplication](https://en.wikipedia.org/wiki/Matrix_multiplication) between two or more gates or states
* `conjugate` calculates the [complex conjugate](https://en.wikipedia.org/wiki/Complex_conjugate) of a number, a vector of numbers, or a matrix of numbers

The tensor product is used to create state vectors with two or more qubits or to create quantum gates that operate in parallel.

Matrix multiplication is used to combine quantum gates sequentially, or to pass a state vector through a quantum gate.

### Creating a State Vector

We can create the state vectors for the numbers `0` (or $|0\rangle$) and `2` (or $|10\rangle$) based on their binary representations

In [11]:
print(bin(0), qgates.qfn.state(0))

0b0 [1 0]


In [12]:
print(bin(2), qgates.qfn.state(2))

0b10 [0 0 1 0]


### Calculating the Tensor Product

The `tens` function is mostly a wrapper around numpy's `kron` function except that it can take more than two numpy `ndarray`s as arguments.

In [13]:
qgates.qfn.tens(
    qgates.states.QB0,
    qgates.states.QB1
)

array([0, 1, 0, 0])

In [14]:
qgates.qfn.tens(
    qgates.gates.IDEN,
    qgates.gates.NOT
)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

### Performing Matrix Multiplication

Similarly, the `matmul` function is a wrapper around numpy's `matmul` function.

In [15]:
qgates.qfn.matmul(
    qgates.gates.NOT,
    qgates.states.QB0
)

array([0, 1])

Alternatively, you can use the `@` operator to perform matrix multiplication.

In [16]:
qgates.gates.HAD

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [17]:
(qgates.gates.HAD @ qgates.gates.HAD
).round(16) # Compensating for rounding-error for simplicity

array([[1., 0.],
       [0., 1.]])

### Calculate the Complex Conjugate

Again, this is a wrapper around numpy's `conjugate` function.

In [18]:
qgates.qfn.conjugate(10) # No imaginary part

10

In [19]:
qgates.qfn.conjugate(10+1j) # Imaginary part

(10-1j)

In [20]:
qgates.qfn.conjugate([
    [2j,1],
    [2,1j]
])

array([[0.-2.j, 1.-0.j],
       [2.-0.j, 0.-1.j]])